version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: user
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - mongodb
            - rabbitmq

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest

volumes:
    mongodb_data:
